language: emacs-lisp
sudo: false
env:
  # Run all unit tests on both Emacs versions
  - TRAVIS_BUILD=unit EMACS_VERSION=24
  - TRAVIS_BUILD=unit EMACS_VERSION=snapshot
  - TRAVIS_BUILD=manual EMACS_VERSION=snapshot
before_install:
  - export PATH="$HOME/.cask/bin:$HOME/bin:$PATH"
  - make -f travis.mk before_install
install:
  - make -f travis.mk install
script:
  - make -f travis.mk script
matrix:
  # Fast fail if any job fails.  We don't need to run all integration tests, if
  # the unit tests fail already.
  fast_finish: true
