language: emacs-lisp
env:
  - EMACS=emacs24
  # Flycheck must compile cleanly on latest Emacs
  - EMACS=emacs-snapshot EMACSFLAGS="--eval '(setq byte-compile-error-on-warn t)'"
before_install:
  # Provision the test environment
  - sudo add-apt-repository -y ppa:rquillo/ansible
  - sudo apt-get update -y -q
  - sudo apt-get install -y ansible
  # Skip Cabal and Cran packages on Travis CI, because they take too much time
  # to build
  - ansible-playbook -i playbooks/travis_inventory --tags language-texinfo --skip-tags=cabal,cran -v playbooks/site.yml
  - source /etc/profile
  - export PATH="${GOPATH}/bin:${HOME}/.local/bin:$PATH"
script:
  - make texinfo
