- name: Setup Vagrant VM for Flycheck
  hosts: default
  gather_facts: false
  sudo: true
  roles:
    - base-locale
    - {role: base-login, home: /home/vagrant/}
    - emacs24
    - emacs-snapshot
    - cask
    - languages

- name: Setup testing environment on Travis CI
  hosts: travisci
  gather_facts: false
  vars:
    # Many environments are already present on Travis CI
    nodejs_preinstalled: true
    clang_preinstalled: true
    ruby_preinstalled: true
    java_preinstalled: true
    go_preinstalled: true
    # Rely on the default Go environment of Travis CI
    go_env: {}
    # Install pip packages as user
    python_pip_extra_args: '--user'
  roles:
    - {role: emacs24, when: "lookup('env', 'EMACS') == 'emacs24'"}
    - {role: emacs-snapshot, when: "lookup('env', 'EMACS') == 'emacs-snapshot'"}
    - cask
    - languages
